<?php

declare(strict_types=1);

namespace He4rt\Organization\Filament\Resources\Recruitment\JobRequisitions\Pages\Kanban\Actions;

use Filament\Actions\Action;
use Filament\Infolists\Components\RepeatableEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;

class ViewCandidateAction extends Action
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->slideOver()
            ->label(__('recruitment::filament.requisition.kanban.actions.view_candidate.label'))
            ->icon(Heroicon::Eye)
            ->schema(fn (Schema $schema) => $schema->components([
                Section::make(__('recruitment::filament.requisition.kanban.sections.candidate_information'))
                    ->schema([
                        TextEntry::make('candidate.user.name')
                            ->label(__('users::labels.name')),
                        TextEntry::make('candidate.user.email')
                            ->label(__('users::labels.email')),
                        TextEntry::make('status')
                            ->badge(),
                    ]),
                Section::make(__('recruitment::filament.requisition.kanban.sections.application_comments'))
                    ->schema([
                        RepeatableEntry::make('comments')
                            ->schema([
                                TextEntry::make('author.name'),
                                TextEntry::make('content')
                                    ->columnSpan(2),
                            ]),
                    ]),
            ])
            );
    }

    public static function getDefaultName(): ?string
    {
        return 'kanban-view-candidate';
    }
}
